---
# follows the same parameter structure as the DB extractor configuration
cognite: # kwargs to pass to the CogniteClient, Environment variable format: ${ENVIRONMENT_VARIABLE}
  # host: https://${EXTPIPES_CDF_CLUSTER}.cognitedata.com/
    host: https://westeurope-1.cognitedata.com
    project: cdf-bootcamp-51-test
  #
  # AAD IdP login credentials:
  #
    idp-authentication:
        #client-name: extpipes-cli
        client-id: 5a97a093-c5c6-4351-a67a-4159ee51379a
        secret: dW28Q~BR3SkvFmQXlTBel3kmQ5bYA6xJHPWdNc.E
        scopes:
            - https://westeurope-1.cognitedata.com/.default
        token_url: https://login.microsoftonline.com/16e3985b-ebe8-4e24-9da4-933e21a9fc81/oauth2/v2.0/token

logger:
    file:
        path: ./logs/extpipes-deploy.log
        level: INFO
    console:
        level: INFO

# extpipe-pattern only documentation atm
extpipe-pattern: '{source}:{short-name}:{rawtable-name}:{suffix}'

# can contain multiple contacts, can be overwritten on pipeline level
default-contacts:
    - name: prakash-bajpai
      email: pbajpai@slb.com
      role: Bootcamp 51 Administrator
      send-notification: true

rawdbs:
  # list of raw-dbs > containing rawtables > containing pipelines
    - rawdb-name: src:001:sap:db
      dataset-external-id: src:001:sap:ds
      short-name: sap
      rawtables:
          - rawtable-name: assets
            pipelines:
        # source is a short-name identifying the pipeline source being
        # a 'db-extractor (db)', an 'Azure Function (az-func)',
        # or 'Azure Data Factory (adf)', 'Python script (py)', ..
                - source: csv
                  schedule: On trigger
                  contacts:
                      - name: prakash-bajpai
                        email: pbajpai@slb.com
                        role: Bootcamp 51 Administrator
                        send-notification: false
    - rawdb-name: src:002:opcua:db
      dataset-external-id: src:002:opcua:ds
      short-name: opcua
      rawtables:
          - rawtable-name: datapoints
            pipelines:
        # source is a short-name identifying the pipeline source being
        # a 'db-extractor (db)', an 'Azure Function (az-func)',
        # or 'Azure Data Factory (adf)', 'Python script (py)', ..
                - source: ice-cream-api
                  schedule: On trigger
                  contacts:
                      - name: prakash-bajpai
                        email: pbajpai@slb.com
                        role: Bootcamp 51 Administrator
                        send-notification: false
